#!/bin/bash

[[ ! -f .env ]] && echo "Please create .env file with valid user NOTIFICATION_UID" && exit 1

set -a # automatically export all variables
source .env
set +a

[[ -z $NOTIFICATION_UID ]] && NOTIFICATION_UID="1000"

cd files

cp 99-simple-usb-automount.rules "$2"/etc/udev/rules.d/

if [[ "$1" == "ro" ]]; then
	sed 's/mntopts="/&ro,/' simple-usb-automount > "$2"/usr/local/bin/simple-usb-automount
else
	cp simple-usb-automount "$2"/usr/local/bin/
fi
chmod +x "$2"/usr/local/bin/simple-usb-automount

sed "s/{UID}/$NOTIFICATION_UID/; s/{USER}/$(getent passwd "$NOTIFICATION_UID" | cut -d: -f1)/" simple-usb-automount@.service > "$2"/etc/systemd/system/simple-usb-automount@.service

systemctl daemon-reload

udevadm control --reload-rules

echo "Done"
