#!/bin/bash
# /usr/local/bin/simple-usb-automount

set -e

mnt="/run/mount/usb"
mntopts_ntfs="user,umask=0000"
mntopts_ext4="rw"
dev="/dev/$2"

mkdir "$mnt" -p
findmnt $mnt || sudo mount -t tmpfs tmpfs $mnt

get_attrs () {
    for attr in TYPE LABEL; do
        eval "MTDEV_$attr"="$(blkid -s $attr -o value /dev/$1)" || true
    done
}

# function to unmount and cleanup
unmount_and_cleanup() {
    umount "$mnt/$MTDEV_LABEL" || true
    rmdir "$mnt/$MTDEV_LABEL" || true
}

if [[ "$1" == "a" ]]; then
    for part in $(lsblk -nro name "$dev" | tac); do
        get_attrs $part
        if [[ ! -v "mntopts_$MTDEV_TYPE" ]] || [[ -z "$MTDEV_LABEL" ]]; then
            continue
        fi
        mntopts="mntopts_$MTDEV_TYPE"
        mkdir "$mnt/$MTDEV_LABEL" -p
        mount "/dev/$part" "$mnt/$MTDEV_LABEL" -o "${!mntopts}"
        if [[ "$?" -eq 0 ]]; then
	    #sudo -u "$USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$UID/bus" notify-send "Mounted /dev/$part at $mnt/$MTDEV_LABEL"
        else
            unmount_and_cleanup
        fi
    done
else
    for part in $(ls "$mnt/" | grep "^$2"); do
        get_attrs $part
        unmount_and_cleanup
    done
fi
