#!/bin/bash

mnt="/run/mount/usb/"
mntopts="user,umask=0000"
dev="/dev/$2"

mkdir /run/mount/usb -p
findmnt /run/mount/usb || sudo mount -t tmpfs tmpfs /run/mount/usb

get_name () {
	blkid -s LABEL -o value /dev/$1
}

if [[ "$1" == "a" ]]; then
	for part in $(lsblk -nro name "$dev" | tac)
	do
		name=$(get_name $part)
		[ -z "$name" ] && continue #if no label set, do nothing
		mkdir "$mnt$name" -p
		mount "/dev/$part" "$mnt$name" -o "$mntopts"
		if [[ "$?" -eq 0 ]]; then
			sudo -u "$DISP_USER" DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$DISP_UID/bus" notify-send "Mounted /dev/$part at $mnt$name"
		else
			rmdir "$mnt$name"
		fi
	done
else
	for part in $(ls "$mnt" | grep "^$2")
	do
		name=$(get_name $part)
		umount "$mnt$name"
		rmdir "$mnt$name"
	done
fi
